### PR TITLE
[Feature] Dedicated MMClsWandbHook for MMClassification (Weights and Biases Integration)

### PR DESCRIPTION
**Pull request by ayulockin**
I have raised a [PR](https://github.com/open-mmlab/mmdetection/pull/7459) in MMDetection contributing a dedicated `MMDetWandbHook` for MMDetection. I was playing around with MMClassification and realized that MMClassification can use a similar dedicated hook (with few minor modifications).

## Motivation

The goal of this PR is to contribute a dedicated Weights and Biases hook for MMClassification.

## Modification

The PR adds two new files:
- `wandblogger_hook.py` where all the Weights and Biases related logic lives and,
- `eval_hooks.py` was added so that the `MMClsWandbHook` can reuse the validation results. 

The feature can easily be used this:
```
log_config = dict(
            interval=10,
            hooks=[
                dict(type='MMClsWandbHook',
                     wandb_init_kwargs={
                         'entity': WANDB_ENTITY,
                         'project': WANDB_PROJECT_NAME
                     },
                     log_checkpoint=True,
                     log_checkpoint_metadata=True,
                     num_eval_images=100)
            ])
```

## Use cases (Optional)

Here are some of the use cases that this PR introduces and should be helpful to the community in general.

### Metrics

* The WandbLogger will automatically log training and validation metrics.
* It will log system (CPU/GPU) metrics.

https://user-images.githubusercontent.com/31141479/161776566-57c59402-a16b-4940-a90a-76b64963a4d1.mov

### Checkpointing with Metadata

If `log_checkpoint` is True, the checkpoint saved at every checkpoint interval will be saved as W&B Artifacts. On top of this, if `log_checkpoint_metadata` is True, every checkpoint artifact will have metadata associated with it as shown in the recording below. 

https://user-images.githubusercontent.com/31141479/161777072-cd00f1ee-aa24-42a4-b47f-9c915600a2f4.mov

### Log Model Prediction 🎉

If `num_eval_images > 0`, at every evaluation interval, the`MMClsWandbHook` logs the model prediction as interactive W&B Tables. To know more about W&B Tables, please refer to the docs [here](https://docs.wandb.ai/guides/data-vis). The 'MMClsWandbHook' logs the predicted class labels along with ground truth labels. 

https://user-images.githubusercontent.com/31141479/161784564-51943f43-53c8-41cf-a920-4d70e67bdc9b.mov

## Checklist

**Before PR**:

- [x] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [x] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [x] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by mzr1996** [comment]
Looks good, but I haven't used Wandb, I will try it recently. 👍

**Comment by ayulockin** [comment]
> Looks good, but I haven't used Wandb, I will try it recently. 👍

Looking forward to your feedback.

**Comment by ayulockin** [comment]
Hey @mzr1996, did you get a chance to play with W&B. Would love your feedback on this work?

**Comment by ayulockin** [comment]
Hey @mzr1996, sorry to bug you again but would love it if you can give some feedback on the hook that I have implemented. I think it will add value to the community. :)

**Comment by mzr1996** [comment]
> Hey @mzr1996, sorry to bug you again but would love it if you can give some feedback on the hook that I have implemented. I think it will add value to the community. :)

Sorry for the late reply. This function is planned to be merged in the version v0.23.1, and I'll review it today.

**Comment by ayulockin** [comment]
Thanks for the reply. Looking forward tot he review.

**Comment by mzr1996** [comment]
Hello, I have reviewed your PR and made some modifications. You can check the difference [here](https://github.com/ayulockin/mmclassification/pull/1)
If you think my PR works well, please merge that PR, and then this PR will be updated.

**Comment by ayulockin** [comment]
Hey @mzr1996 I have tested the changes and made a few of my own (they are minor). Can you please take a look and let me know if anything else is needed. Thank you again for a really helpful PR.

**Comment by ayulockin** [comment]
Hey @mzr1996, would love to get a confirmation about the changes made to the PR after your feedback. Also can you let me  know what else is required from my end. Thanks. :)

**Comment by ayulockin** [comment]
Hey @mzr1996, apologises for the ping again. But I would like to know if anything else is needed for this PR?

**Review by mzr1996 — APPROVED** [review]
Looks good

**Comment by lsch0lz** [comment]
Thanks for implementing this hook! I just tried it out, but can't quite get it to run. How do I log into my WandDB Account or do I have to specify somewhere an API Key to log the informations into my WanDB Project? Training works as usual, but I cant see the logs in the specified WanDB Project.

My config file looks like this:
```
_base_ = [
    '../_base_/models/swin_transformer/tiny_224.py',
    '../_base_/datasets/imagenet_bs64_swin_224.py',
    '../_base_/schedules/imagenet_bs1024_adamw_swin.py',
    '../_base_/default_runtime.py'
]

# schedule settings
optim_wrapper = dict(clip_grad=dict(max_norm=5.0))

# Dataset
data_root = 'XXX'
train_dataloader = dict(
    dataset=dict(
        type='CustomDataset',
        data_root=data_root,
        ann_file='',
        data_prefix='train',
    ))
val_dataloader = dict(
    dataset=dict(
        type='CustomDataset',
        data_root=data_root,
        ann_file='',
        data_prefix='val',
    ))
test_dataloader = dict(
    dataset=dict(
        type='CustomDataset',
        data_root=data_root,
        ann_file='',
        data_prefix='test',
    ))

# Logging
log_config = dict(
            interval=10,
            hooks=[
                dict(type='MMClsWandbHook',
                     wandb_init_kwargs={
                         'entity': "MY_USER_NAME",
                         'project': "MY_PROJECT_NAME"
                     },
                     log_checkpoint=True,
                     log_checkpoint_metadata=True,
                     num_eval_images=100)
            ])
```

**Pull request merged**
