### PR TITLE
[Enhancement] Update VAN

### PR DESCRIPTION
**Pull request by okotaku**
### 1. Use new Architecture named series

previous arch names :  'tiny', 'small', 'base' and 'large'
previous arch names :  'b0', 'b1', 'b2' and 'b3' .....

And the 'b0' is totally equal to 'tiny'; the 'b1' is totally equal to 'small'; the 'b2' is totally equal to 'base'; the 'b3' is totally equal to 'large'.

###  2. Add new release weight form [Official repo](https://github.com/Visual-Attention-Network/VAN-Classification) 

- add 'b4' weight with ACC of 84.13@224
- add 'b4' ,'b5', 'b6' pre-trained weights in ImageNet-21k dataset

## Checklist

**Before PR**:

- [x] Pre-commit or other linting tools are used to fix the potential lint issues.
- [x] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [x] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [x] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [x] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [x] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Review by Ezra-Yu — CHANGES_REQUESTED** [review]
I think it's better to keep "tiny", "small", "large" structs before adding 'b0', 'b1' etc. This will be compatible with previous versions. You can add a new config name 'b0' but use the same checkpoint with 'tiny'.

**Review by Ezra-Yu — APPROVED** [review]
LGTM.

**Review by mzr1996 — APPROVED** [review]

**Comment by okotaku** [comment]
@Ezra-Yu 
Should I make this PR again for dev-1.x?
Or do you plan to incorporate PRs that have been merged into dev by the mmlab team into dev-1.x as well?

**Comment by Ezra-Yu** [comment]
@okotaku  Welcome to migrating it to dev-1.x if it's convenient for you.

Yes, we plan to migrate the last few PRs on `dev` to `dev_1.x` in the remaining months of this year.

Although we need to sync `master` with `1.x` updates in principle. But if time is not enough, **supporting new features to `1.x` has a higher priority**. So next time, if you want to add a new feature, please add it directly to the `1.x` branch.

**Pull request merged**
