### PR TITLE
[Fix] Fix mmcv dep version in mminstall.txt

### PR DESCRIPTION
**Pull request by mzr1996**

### CODE REVIEW

**Comment by Ezra-Yu** [comment]
the [requirements.txt ](https://github.com/mzr1996/mmclassification/blob/25b557dc6bb20adc07632aae2a70b5b82ab88c2e/requirements.txt) do not contain requirements/mminstall.txt.

**Comment by Ezra-Yu** [comment]
Why the mmcv-full version should higher than 1.3.8?

**Comment by mzr1996** [comment]
> the [requirements.txt ](https://github.com/mzr1996/mmclassification/blob/25b557dc6bb20adc07632aae2a70b5b82ab88c2e/requirements.txt) do not contain requirements/mminstall.txt.

`mminstall.txt` is not necessary for `requirements.txt`, and it's only used by mim.

Refers to https://github.com/open-mmlab/mmdetection/blob/master/requirements.txt

**Comment by mzr1996** [comment]
> Why the mmcv-full version should higher than 1.3.8?

It's from the [install docs](https://github.com/open-mmlab/mmclassification/blob/master/docs/install.md#requirements).
According to the requirement of `mmcv`.

**Review by Ezra-Yu — APPROVED** [review]
LGTM

**Review by Ezra-Yu — APPROVED** [review]
LGTM

**Pull request merged**
