### PR TITLE
[Fix] Fix the torchserve

### PR DESCRIPTION
**Pull request by marouaneamz**
## Modification

after our discussion in #1141  I just changed mmcv to mmengine to mmcls2torchserve.

1. fix torch serve; 
2. remove deprecated deploy tools.

### CODE REVIEW

**Comment by Ezra-Yu** [comment]
@marouaneamz  Some other places also need to be modified.
Can I make some modifications and push it to your branch?

**Comment by Ezra-Yu** [comment]
@marouaneamz  Sorry, I have no permission to push code into your repo. Can you invite me to cooperate with your repo.?
refer to this [GitHub doc](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository).

**Comment by marouaneamz** [comment]
@Ezra-Yu i invite you to my repository can you check it is good

**Review by mzr1996 — APPROVED** [review]

**Comment by OpenMMLab-Miao** [comment]
Hi @marouaneamz ！First of all, we want to express our gratitude for your significant PR in the MMCls project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/raweFPmdzG

If you have WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Comment by OpenMMLab-Miao** [comment]
Hi @CLAassistant ！First of all, we want to express our gratitude for your significant PR in the MMCls project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request merged**
