### PR TITLE
[Feature] Support EVA

### PR DESCRIPTION
**Pull request by okotaku**
## Motivation

paper: https://arxiv.org/abs/2211.07636
code: https://github.com/baaivision/EVA
issue: https://github.com/open-mmlab/mmclassification/issues/1219

## Modification

~~In addition, I fixed a bug in BEiT that caused ffn's add_identity to be True.~~ fixed in https://github.com/open-mmlab/mmclassification/pull/1234
And fixed sklearn deprecated error.

## Checklist

**Before PR**:

- [x] Pre-commit or other linting tools are used to fix the potential lint issues.
- [x] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [x] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [x] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [x] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [x] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by Ezra-Yu** [comment]
the official repo  https://github.com/baaivision/EVA has released MAE style EVA model, Could you convert them all together?

**Comment by okotaku** [comment]
@Ezra-Yu 
You mean 'eva_psz14' and 'eva_psz14to16' ?
https://github.com/baaivision/EVA/tree/master/eva

I thought this convert script was fine for its, any improvements?

**Comment by Ezra-Yu** [comment]
> @Ezra-Yu You mean 'eva_psz14' and 'eva_psz14to16' ? https://github.com/baaivision/EVA/tree/master/eva


this https://github.com/baaivision/EVA/tree/master/eva#eva-l-learning-better-mim-representations-from-eva-clip; `eva_l_psz14` and `eva_l_psz14_21k_ft`

**Comment by okotaku** [comment]
I got it.

**Comment by okotaku** [comment]
@Ezra-Yu Done!

**Comment by okotaku** [comment]
@mzr1996 It looks good.

**Review by mzr1996 — APPROVED** [review]
LGTM

**Pull request merged**
