### PR TITLE
[Feature] MultiheadAttentionPooling

### PR DESCRIPTION
**Pull request by chagmgang**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

This PR is adding feature of multi head attention pooling neck.
This feature is inspired by [Set Transformer: A Framework for Attention-based
Permutation-Invariant Neural Networks](http://proceedings.mlr.press/v97/lee19d/lee19d.pdf).

## Modification

The multi head attention pooling neck was implemented with maintaining the code style of the already existing [hr_fuse](https://github.com/open-mmlab/mmclassification/blob/master/mmcls/models/necks/hr_fuse.py).

## Use cases (Optional)

The use cases of this feature is simply seen in test code.
However, surely the usage of this function is presented below.
```
in_channels = (18, 32, 64, 128)
neck = HRFuseScales(in_channels=in_channels, out_channels=1024)

feat_size = 56
inputs = []
for in_channel in in_channels:
    input_tensor = torch.rand(3, in_channel, feat_size, feat_size)
    inputs.append(input_tensor)
    feat_size = feat_size // 2

outs = neck(tuple(inputs))
assert isinstance(outs, tuple)
assert len(outs) == 1
assert outs[0].shape == (3, 1024, 7, 7)
```

## Checklist

**Before PR**:

- [x] Pre-commit or other linting tools are used to fix the potential lint issues.
- [x] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [x] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [x] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [x] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [x] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by Ezra-Yu** [comment]
Thanks for your contribution and we appreciate it a lot. We will review it soon.

**Comment by mzr1996** [comment]
Could you provide any config file which use this neck?

**Comment by chagmgang** [comment]
> Could you provide any config file which use this neck?

```
model = dict(
    type='ImageClassifier',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0,1,2,3,),
        style='pytorch',
    ),
    neck=dict(
        type='MultiheadAttentionPooling',
        in_channels=(256, 512, 1024, 2048),
        num_heads=(8, 8, 8, 8),
        out_channels=2048,
    ),
    head=dict(
        type='LinearClsHead',
        num_classes=1000,
        in_channels=2048,
        loss=dict(
            type='LabelSmoothLoss',
            label_smooth_val=0.1,
            num_classes=1000,
            reduction='mean',
            loss_weight=1.0),
        topk=(1, 5),
        cal_acc=False))
```
or

```
model = dict(
    type='ImageClassifier',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(3,),
        style='pytorch',
    ),
    neck=dict(
        type='MultiheadAttentionPooling',
        in_channels=[2048],
        num_heads=[8],
        out_channels=2048,
    ),
    head=dict(
        type='LinearClsHead',
        num_classes=1000,
        in_channels=2048,
        loss=dict(
            type='LabelSmoothLoss',
            label_smooth_val=0.1,
            num_classes=1000,
            reduction='mean',
            loss_weight=1.0),
        topk=(1, 5),
        cal_acc=False))
```

**Comment by OpenMMLab-Assistant-004** [comment]
Hi @chagmgang ！We are grateful for your efforts in helping improve mmpretrain open-source project during your personal time. 

Welcome to join OpenMMLab Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA
If you have a WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）

Thank you again for your contribution❤

**Pull request closed without merging**
