### PR TITLE
add chinese ipynb tutorial

### PR DESCRIPTION
**Pull request by wangruohui**

### CODE REVIEW

**Comment by mzr1996** [comment]
> @mzr1996 Could you please also review this PR?

I'm already reviewing, but found some problems about weight init, and it's blocked by #318 now

**Review by mzr1996 — APPROVED** [review]
I have corrected the tutorials and commit my modification.

**Review by Ezra-Yu — COMMENTED** [review]
in MMClassification_tools_cn.py
1.  I can not get the accuracy of 99.
2.  In the last cell, the dict of results do not have key of 'class_scores'.

**Comment by mzr1996** [comment]
> in MMClassification_tools_cn.py
> 
>     1. I can not get the accuracy of 99.
> 
>     2. In the last cell, the dict of results do not have key of 'class_scores'.

Please try again

**Review by Ezra-Yu — APPROVED** [review]
Look good.

**Pull request merged**
