### PR TITLE
[Feature] Add Pytorch2torchscript

### PR DESCRIPTION
**Pull request by AllentDan**
Hi, this is a working in progress PR for adding TorchScript deployment.
Added tracing judgements to cls_head, linear_head, multi_label_head, multi_label_linear_head and vision_transformer_head.
Added pytorch2torchscript.py.
Added pytorch2torchscript.md

### CODE REVIEW

**Review by AllentDan — COMMENTED** [review]
LGTM

**Comment by ycxioooong** [comment]
Hi, the user 董春玉 did not sign CLA, so the PR is currently stucked before review.

**Comment by AllentDan** [comment]
Hi, @ycxioooong. I forgot to configure the user account before this PR. Is there any way to sign the CLA with default account:
```
 git log pytorch2torchscript
commit 075ee93a4c5f75318fff543f4e391fc6ba51883d (origin/pytorch2torchscript, pytorch2torchscript)
Author: 董春玉 <SENSETIME\dongchunyu@cn3614000311l.domain.sensetime.com>
Date:   Mon May 10 20:43:41 2021 +0800
```

**Comment by ycxioooong** [comment]
You may consider close this PR and re-submit one

**Comment by AllentDan** [comment]
Applied.

**Pull request closed without merging**
