### PR TITLE
use torch.nn.functional.one_hot rewrite convert_to_one_hot

### PR DESCRIPTION
**Pull request by HumberMe**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Torch has the implementation of one-hot, here we can replace the one-hot implemented by MMCLS itself

## Modification

as described above

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [x] Pre-commit or other linting tools are used to fix the potential lint issues.
- [x] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [x] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [x] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [x] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [x] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by Ezra-Yu** [comment]
Thank you for your contribution, please fix the lint refer to the [guide](https://mmclassification.readthedocs.io/en/latest/community/CONTRIBUTING.html#code-style) before we review it.

**Comment by HumberMe** [comment]
> Thank you for your contribution, please fix the lint refer to this [guide](https://mmclassification.readthedocs.io/en/latest/community/CONTRIBUTING.html#code-style) before we review it.

@Ezra-Yu 
I have followed the lint hint to make changes to the codes format, but it looks like the tests didn't restart automatically, what else do I need to do?

**Comment by Ezra-Yu** [comment]
After installing `pre-commit`, the `pre-commit` does not work until you create a commit, 

you could run
```
pre-commit run --all-files
```
in '$MMClassification' to check if there is any style error. then fix it and commit it.

**Comment by HumberMe** [comment]
cannot understand this error:
```
yapf.....................................................................Failed
- hook id: yapf
- files were modified by this hook
```
@Ezra-Yu

**Comment by Ezra-Yu** [comment]
you can let the L117 in one line:
```
    one_hot_targets = F.one_hot(targets.long().squeeze(-1), num_classes=classes)
```
and run ```pre-commit run --all-files``` twice, the `pre-commit` would modify this line automatically.
it would be:
```
    one_hot_targets = F.one_hot(
        targets.long().squeeze(-1), num_classes=classes)
```

**Comment by HumberMe** [comment]
> That means the pre-commit would modify the code automatically.
> 
> you can let the L117 in one line:
> 
> ```
>     one_hot_targets = F.one_hot(targets.long().squeeze(-1), num_classes=classes)
> ```
> 
> and run `pre-commit run --all-files` twice in command, the `pre-commit` would modify this line automatically. it would be:
> 
> ```
>     one_hot_targets = F.one_hot(
>         targets.long().squeeze(-1), num_classes=classes)
> ```

doesn't seem like a necessary change, currently I cannot install&use pre-commit successfully for some permission problem, so is there a work-around?

**Comment by Ezra-Yu** [comment]
> me permission problem, s

OK, get it. We would modify it later when reviewing.

**Comment by HumberMe** [comment]
> > me permission problem, s
> 
> OK, get it. We would modify it later when reviewing.

that's great help

**Review by Ezra-Yu — APPROVED** [review]
LGTM.

**Pull request merged**
