### PR TITLE
[Feature] Add EfficientNet backbone and converted ckpts

### PR DESCRIPTION
**Pull request by LXXXXR**
Hi,
This pull request is based on #41.

Several things to note:

1. EfficientNet b0, b1, b2,b3, b4, b5, b6, b7, b8 edge-tpu-s, edge-tpu-m are added
2. ckpts are converted from https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet
3. pre-processing follows the tensorflow style crop&resize

### CODE REVIEW

**Review by ycxioooong — APPROVED** [review]
looks fine

**Comment by ycxioooong** [comment]
Please resolve the conflicts by using BaseModule at your working time. Thanks.

**Comment by fcakyon** [comment]
@LXXXXR @ycxioooong so efficientnet backbone pr is abandoned?

**Comment by mzr1996** [comment]
> @LXXXXR @ycxioooong so efficientnet backbone pr is abandoned?

Yes, both members have left and nobody continues it now.
But recently, we will restart EfficientNet work, and implement it collaborating with the mmdet team.

**Comment by mzr1996** [comment]
Closed by #649

**Pull request closed without merging**
