### PR TITLE
 fix performance issue in convnext DDP train

### PR DESCRIPTION
**Pull request by 790475019**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

There are flowing warning when use dist_train.sh to train convnext 
> [W reducer.cpp:347] Warning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.

## Modification

call contiguous after permute in layernorm, and the performance actually improve 3x in my test 

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [x] Pre-commit or other linting tools are used to fix the potential lint issues.
- [x] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [x] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [x] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Review by mzr1996 — APPROVED** [review]
LGTM, I have tested it and this modification can slightly accelerate the training.

**Comment by kamzero** [comment]
> the performance actually improve 3x in my test

Hi! May I ask whether this warning only affects the training speed and convergence speed, or will it affect the accuracy?

**Comment by 790475019** [comment]
> > the performance actually improve 3x in my test
> 
> Hi! May I ask whether this warning only affects the training speed and convergence speed, or will it affect the accuracy?

I do not do the ablation experiment, but the model i trained before fixing the bug works normally, so i think it only affects the training speed.

**Comment by OpenMMLab-Assistant005** [comment]
Hi @790475019 ！First of all, we want to express our gratitude for your significant PR in the project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request merged**
